#This file contains data settings for the main file.
gravityFlip =  False
gravityValue = -1000
ballMass = 5E3
ballRadius = 5
displayText = ""
windowSizeX = 1920
windowSizeY = 1080
FrictionMultiplier = 0.2
ElasticityMultiplier = 0
SoundPath = 'sound.mp3'
MusicPath = 'music.mp3'
Music = True
psi = 0.5
WindowsSizeFactorX = windowSizeX / 640
WindowsSizeFactorY = windowSizeY / 480 
StrokeThickness = 5
SegmentOneXMultiplier = WindowsSizeFactorX
SegmentTwoXMultiplier = WindowsSizeFactorX
SegmentOneYMultiplier = WindowsSizeFactorY
SegmentTwoYMultiplier = WindowsSizeFactorY 
Shape = "circle"
